export const baseURL ="https://wowfy.in/doutya_recruit/api";
export const baseImgURL ="https://wowfy.in/doutya_recruit/photos/";
export const baseVidUrl ="https://wowfy.in/doutya_recruit/videos/";
// export const baseURL ="http://192.168.1.9/Zen/doutya/api";
// export const baseImgURL ="http://192.168.1.9/Zen/doutya/photos/";
// export const baseVidUrl ="http://192.168.1.9/Zen/doutya/videos/";
// export const baseURL ="http://172.20.10.4/Zen/Wowfy-api-projects/wowfy-location/api";
// export const baseImgURL ="http://172.20.10.4/Zen/Wowfy-api-projects/wowfy-location/photos/";
// export const baseVidUrl ="http://172.20.10.4/Zen/Wowfy-api-projects/wowfy-location/videos/";
